version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kanbin-db
    restart: always
    environment:
      - POSTGRES_USER=kanbin
      - POSTGRES_PASSWORD=kanbin
      - POSTGRES_DB=kanbin_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
